query getLessonsByLevel($level: String!){
  lessons(
    where:{level:{_eq:$level}}
    order_by:{title:asc}){
      id
      thumbnail
      level
      title
      discussion
      transcript
      vocabulary
      }
  }