query getLatestLessonsOfUser($userId: String!){
  user_lessons(
    where:{user_id:{_eq:$userId}}
    order_by:{lastTimeWatched:desc}, 
    limit:5){
    lastTimeWatched
    lesson{
      id
      thumbnail
      level
      title
      discussion
      transcript
      vocabulary
      }
  }
}